from aiogram import types

keyboard = types.InlineKeyboardMarkup(1)
mailing = types.InlineKeyboardButton('Xabar', callback_data='mailing')
statistics = types.InlineKeyboardButton('Statistika', callback_data='statistics')
prices = types.InlineKeyboardButton('Narxni o`zgartirish', callback_data='update_prices')
update_qiwi = types.InlineKeyboardButton('QIWIni o`zgartirish', callback_data='update_qiwi')
update_yoo = types.InlineKeyboardButton('YOOMONEYni o`zgartirish', callback_data='update_yoo')
update_help_link = types.InlineKeyboardButton('Akkaunt TPni o`zgartirish', callback_data='update_help_link')
update_referal_percentage = types.InlineKeyboardButton('Referallar foizini o`zgartirish', callback_data='update_percentage')
show_referals = types.InlineKeyboardButton('Referallar', callback_data='show_referals')
edit_referals = types.InlineKeyboardButton('Referal foizini o`zgartirish', callback_data='update_percentage_ind')
update_channel_link = types.InlineKeyboardButton('Kanal ssilkasini o`zgartirish', callback_data='update_channel_link')
add_admin = types.InlineKeyboardButton('Admin qo`shish', callback_data='add_admin')
remove_admin = types.InlineKeyboardButton('Adminni o`chirish', callback_data='remove_admin')
switch_subscription_check = types.InlineKeyboardButton('Obunani tekshirishni Yoqish/O`chirish', callback_data='switch_subscription_check')
qiwi_balance = types.InlineKeyboardButton('Xisob QIWI', callback_data='qiwi_balance')
keyboard.add(mailing, statistics, prices)
keyboard.row(update_qiwi, update_yoo)
keyboard.add(update_help_link, update_referal_percentage, show_referals, edit_referals, add_admin, remove_admin, update_channel_link, switch_subscription_check, qiwi_balance)